/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ejemplo.gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mony
 */
public class JFLogin extends javax.swing.JFrame {

    private final String USUARIO = "java";
    private final String PASS = "java";

    /**
     * Creates new form JFLogin
     */
    public JFLogin() {
        initComponents();
        setTitle("Login");
        setLocationRelativeTo(null);

    }

    /**
     * Creates new form JFLogin
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtPassword = new javax.swing.JTextField();
        jbIngresar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jbIngresar.setText("Ingresar");
        jbIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbIngresar)
                            .addComponent(jtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jbIngresar)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIngresarActionPerformed
        if (jtUsuario.getText().equals("") || jtPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Los campos: Usuario y/o Password son requeridos!", "Login", JOptionPane.ERROR_MESSAGE);
        } else {
            /*  if(jtUsuario.getText().equals(USUARIO) && jtPassword.getText().equals(PASS))
                JOptionPane.showMessageDialog(this,"Bienvenido <java> al sistema!", "Login", JOptionPane.INFORMATION_MESSAGE);
                else
                JOptionPane.showMessageDialog(this,"Usuario y/o Password incorrectos!", "Login", JOptionPane.ERROR_MESSAGE);*/
            try {
                int usuario = -1;
                String sql = "SELECT * " +
                             "FROM USUARIOS t " +
                             "WHERE t.NOMBRE = '" + jtUsuario.getText() + "' " +
                             "AND t.PASSWORD = '" + jtPassword.getText() + "'";
//URL de conexión, usuario, password
                Connection cnn = DriverManager.getConnection("jdbc:derby://localhost:1527/Prueba", "ADMINISTRADOR", "admin");
                //Crear comando
                Statement stmt = cnn.createStatement();
                //Ejecutaar y obtener un conjunto de resultados
                ResultSet rs =  stmt.executeQuery(sql);
                
                if (rs.next()) {                    
                    /*//Acceder a cada campo de la fila
                    int id = rs.getInt("id_usuario");
                    String usuario = rs.getString("nombre");
                    String pass = rs.getString("password");*/
                    usuario = rs.getInt("id_usuario");
                    
                } else {
                    JOptionPane.showMessageDialog(this,"Usuario y/o password incorrectos");
                }
                
                rs.close();
                stmt.close();
                cnn.close();
                
                if(usuario != -1) {
                    
                    new JFGastos (usuario).setVisible(true);
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error. No se puede conectar on la BD");
            }
        }

    }//GEN-LAST:event_jbIngresarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbIngresar;
    private javax.swing.JTextField jtPassword;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
